global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics

  - job_name: 'saleor-dashboard'
    metrics_path: /
    static_configs:
      - targets: ['saleor-dashboard:9000']
