name: CI for Saleor Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_DB: saleor
          POSTGRES_USER: saleor
          POSTGRES_PASSWORD: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: List files for debugging
      run: ls -la && ls -la saleor

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install backend dependencies using Poetry
      run: |
        cd saleor
        poetry install

    - name: Set environment variable
      run: echo "DATABASE_URL=postgresql://saleor:saleor@localhost:5432/saleor" >> $GITHUB_ENV

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 && echo "Postgres is ready" && exit 0
          echo "Waiting for Postgres..."
          sleep 3
        done
        echo "Postgres did not start in time" && exit 1

    - name: Run backend tests
      run: |
        cd saleor
        poetry run pytest
